/* ===================================================================
   Base de datos de señales de tránsito — Manual Categoría D1-D4 Tigre
   Cada señal: { id, categoria, nombre, forma, icono }
   forma: triangulo | triangulo_invertido | circulo_prohibicion | circulo_obligacion |
          octogono | rectangulo_info | rombo_transitoria | rectangulo_transitoria |
          rectangulo_horizontal | circulo_semaforo | figura_agente
   =================================================================== */

const SENALES = [

// ---------------- PREVENCIÓN (triángulo amarillo) ----------------
{ id:"p01", categoria:"Prevención", nombre:"Curva peligrosa", forma:"triangulo", icono:{tipo:"camino", variante:"curva", rotacion:0} },
{ id:"p02", categoria:"Prevención", nombre:"Curva", forma:"triangulo", icono:{tipo:"camino", variante:"curva_suave", rotacion:0} },
{ id:"p03", categoria:"Prevención", nombre:"Curva y contracurva", forma:"triangulo", icono:{tipo:"camino", variante:"doble_curva", rotacion:0} },
{ id:"p04", categoria:"Prevención", nombre:"Curva y contracurva menor", forma:"triangulo", icono:{tipo:"camino", variante:"doble_curva_menor", rotacion:0} },
{ id:"p05", categoria:"Prevención", nombre:"Camino sinuoso", forma:"triangulo", icono:{tipo:"camino", variante:"sinuoso", rotacion:0} },
{ id:"p06", categoria:"Prevención", nombre:"Doble circulación próxima", forma:"triangulo", icono:{tipo:"flecha", doble:true, rotacion:-90} },
{ id:"p07", categoria:"Prevención", nombre:"Estrechamiento de calzada", forma:"triangulo", icono:{tipo:"camino", variante:"angosto"} },
{ id:"p08", categoria:"Prevención", nombre:"Cruce de caminos", forma:"triangulo", icono:{tipo:"camino", variante:"cruz"} },
{ id:"p09", categoria:"Prevención", nombre:"Bifurcación en T", forma:"triangulo", icono:{tipo:"camino", variante:"t"} },
{ id:"p10", categoria:"Prevención", nombre:"Bifurcación en Y", forma:"triangulo", icono:{tipo:"camino", variante:"y"} },
{ id:"p11", categoria:"Prevención", nombre:"Camino lateral (derecha)", forma:"triangulo", icono:{tipo:"camino", variante:"lateral", rotacion:0} },
{ id:"p12", categoria:"Prevención", nombre:"Camino lateral (izquierda)", forma:"triangulo", icono:{tipo:"camino", variante:"lateral", espejo:true} },
{ id:"p13", categoria:"Prevención", nombre:"Empalmes contrarios sucesivos", forma:"triangulo", icono:{tipo:"camino", variante:"empalmes"} },
{ id:"p14", categoria:"Prevención", nombre:"Ciclista", forma:"triangulo", icono:{tipo:"vehiculo", variante:"bicicleta"} },
{ id:"p15", categoria:"Prevención", nombre:"Fin de camino dividido", forma:"triangulo", icono:{tipo:"camino", variante:"fin_dividido"} },
{ id:"p16", categoria:"Prevención", nombre:"Incorporación de tránsito", forma:"triangulo", icono:{tipo:"camino", variante:"incorporacion"} },
{ id:"p17", categoria:"Prevención", nombre:"Rotonda", forma:"triangulo", icono:{tipo:"camino", variante:"rotonda"} },
{ id:"p18", categoria:"Prevención", nombre:"Puente angosto", forma:"triangulo", icono:{tipo:"camino", variante:"angosto"} },
{ id:"p19", categoria:"Prevención", nombre:"Puente móvil", forma:"triangulo", icono:{tipo:"pictograma", nombre:"puente"} },
{ id:"p20", categoria:"Prevención", nombre:"Vientos fuertes laterales", forma:"triangulo", icono:{tipo:"pictograma", nombre:"viento"} },
{ id:"p21", categoria:"Prevención", nombre:"Depresión transversal (badén)", forma:"triangulo", icono:{tipo:"perfil", variante:"baden"} },
{ id:"p22", categoria:"Prevención", nombre:"Elevación transversal (lomo de burro)", forma:"triangulo", icono:{tipo:"perfil", variante:"lomo"} },
{ id:"p23", categoria:"Prevención", nombre:"Túnel vehicular", forma:"triangulo", icono:{tipo:"pictograma", nombre:"tunel"} },
{ id:"p24", categoria:"Prevención", nombre:"Calzada resbaladiza", forma:"triangulo", icono:{tipo:"pictograma", nombre:"resbaladiza"} },
{ id:"p25", categoria:"Prevención", nombre:"Zona de derrumbe", forma:"triangulo", icono:{tipo:"pictograma", nombre:"derrumbe"} },
{ id:"p26", categoria:"Prevención", nombre:"Pendiente peligrosa (bajada)", forma:"triangulo", icono:{tipo:"perfil", variante:"bajada"} },
{ id:"p27", categoria:"Prevención", nombre:"Pendiente peligrosa (subida)", forma:"triangulo", icono:{tipo:"perfil", variante:"subida"} },
{ id:"p28", categoria:"Prevención", nombre:"Obras", forma:"triangulo", icono:{tipo:"pictograma", nombre:"obras"} },
{ id:"p29", categoria:"Prevención", nombre:"Precaución niños jugando", forma:"triangulo", icono:{tipo:"persona", pose:"jugando"} },
{ id:"p30", categoria:"Prevención", nombre:"Cruce de escolares", forma:"triangulo", icono:{tipo:"persona", pose:"escolar"} },
{ id:"p31", categoria:"Prevención", nombre:"Cruce de peatones", forma:"triangulo", icono:{tipo:"persona", pose:"caminando"} },
{ id:"p32", categoria:"Prevención", nombre:"Animales sueltos", forma:"triangulo", icono:{tipo:"pictograma", nombre:"animal"} },
{ id:"p33", categoria:"Prevención", nombre:"Parque nacional", forma:"triangulo", icono:{tipo:"pictograma", nombre:"arbol"} },
{ id:"p34", categoria:"Prevención", nombre:"Proximidad de señal restrictiva", forma:"triangulo", icono:{tipo:"pictograma", nombre:"prohibido_mini"} },
{ id:"p35", categoria:"Prevención", nombre:"Ancho limitado", forma:"triangulo", icono:{tipo:"numero", valor:"3m", flechas:true} },
{ id:"p36", categoria:"Prevención", nombre:"Altura limitada", forma:"triangulo", icono:{tipo:"numero", valor:"4,50m", arriba:true} },
{ id:"p37", categoria:"Prevención", nombre:"Maquinaria agrícola", forma:"triangulo", icono:{tipo:"pictograma", nombre:"tractor"} },
{ id:"p38", categoria:"Prevención", nombre:"Vuelos bajos", forma:"triangulo", icono:{tipo:"pictograma", nombre:"avion"} },
{ id:"p39", categoria:"Prevención", nombre:"Proximidad de semáforo", forma:"triangulo", icono:{tipo:"pictograma", nombre:"semaforo_mini"} },
{ id:"p40", categoria:"Prevención", nombre:"Proyección de piedras", forma:"triangulo", icono:{tipo:"pictograma", nombre:"piedras"} },
{ id:"p41", categoria:"Prevención", nombre:"Paso a nivel", forma:"triangulo", icono:{tipo:"pictograma", nombre:"tren"} },
{ id:"p42", categoria:"Prevención", nombre:"Irregularidad continua", forma:"triangulo", icono:{tipo:"camino", variante:"irregular"} },
{ id:"p43", categoria:"Prevención", nombre:"Proximidad de señal restrictiva (PARE a 100m)", forma:"triangulo", icono:{tipo:"pictograma", nombre:"pare_mini"} },
{ id:"p44", categoria:"Prevención", nombre:"Escuela", forma:"triangulo", icono:{tipo:"persona", pose:"escolar"} },
{ id:"p45", categoria:"Prevención", nombre:"Sentido de circulación", forma:"triangulo", icono:{tipo:"flecha", doble:true, rotacion:0} },
{ id:"p46", categoria:"Prevención", nombre:"Paso a nivel con barrera", forma:"triangulo", icono:{tipo:"pictograma", nombre:"barrera"} },
{ id:"p47", categoria:"Prevención", nombre:"Paso a nivel sin barrera", forma:"triangulo", icono:{tipo:"pictograma", nombre:"tren"} },
{ id:"p48", categoria:"Prevención", nombre:"Paso a nivel con o sin barrera", forma:"triangulo", icono:{tipo:"pictograma", nombre:"tren_triangulo"} },
{ id:"p49", categoria:"Prevención", nombre:"Atención", forma:"triangulo", icono:{tipo:"texto", valor:"!"} },
{ id:"p50", categoria:"Prevención", nombre:"Senda de peatones", forma:"triangulo", icono:{tipo:"persona", pose:"caminando"} },
{ id:"p51", categoria:"Prevención", nombre:"Panel de prevención (a 100m)", forma:"panel", icono:{tipo:"panel", lineas:1} },
{ id:"p52", categoria:"Prevención", nombre:"Panel de prevención (a 200m)", forma:"panel", icono:{tipo:"panel", lineas:2} },
{ id:"p53", categoria:"Prevención", nombre:"Panel de prevención (a 300m)", forma:"panel", icono:{tipo:"panel", lineas:3} },
{ id:"p54", categoria:"Prevención", nombre:"Panel de prevención de obstáculo rígido", forma:"panel", icono:{tipo:"panel", lineas:4} },
{ id:"p55", categoria:"Prevención", nombre:"Panel de prevención de curva (chevron)", forma:"chevron", icono:{tipo:"chevron", rotacion:0} },
{ id:"p56", categoria:"Prevención", nombre:"Cruz de San Andrés (hasta 2 vías férreas)", forma:"cruz_andres", icono:{tipo:"cruzAndres", doble:false} },
{ id:"p57", categoria:"Prevención", nombre:"Cruz de San Andrés (más de 2 vías férreas)", forma:"cruz_andres", icono:{tipo:"cruzAndres", doble:true} },
{ id:"p58", categoria:"Prevención", nombre:"Fin de prevención (derrumbes)", forma:"triangulo", icono:{tipo:"pictograma", nombre:"fin_prevencion"} },

// ---------------- REGLAMENTACIÓN: PROHIBICIÓN (círculo blanco/rojo) ----------------
{ id:"r01", categoria:"Reglamentación", nombre:"Prohibido cambiar de carril", forma:"circulo_prohibicion", icono:{tipo:"pictograma", nombre:"cambiar_carril"} },
{ id:"r02", categoria:"Reglamentación", nombre:"Detención obligatoria (PARE)", forma:"octogono", icono:{tipo:"texto", valor:"PARE"} },
{ id:"r03", categoria:"Reglamentación", nombre:"No avanzar", forma:"circulo_prohibicion", icono:{tipo:"flecha", rotacion:-90, tachada:true} },
{ id:"r04", categoria:"Reglamentación", nombre:"Prohibido girar a la izquierda", forma:"circulo_prohibicion", icono:{tipo:"flecha", rotacion:180, curva:true, tachada:true} },
{ id:"r05", categoria:"Reglamentación", nombre:"Prohibido girar en U", forma:"circulo_prohibicion", icono:{tipo:"pictograma", nombre:"giro_u", tachada:true} },
{ id:"r06", categoria:"Reglamentación", nombre:"Contramano", forma:"circulo_prohibicion", icono:{tipo:"barra"} },
{ id:"r07", categoria:"Reglamentación", nombre:"Ceda el paso", forma:"triangulo_invertido", icono:{tipo:"texto", valor:""} },
{ id:"r08", categoria:"Reglamentación", nombre:"Prohibido tocar bocina", forma:"circulo_prohibicion", icono:{tipo:"pictograma", nombre:"bocina", tachada:true} },
{ id:"r09", categoria:"Reglamentación", nombre:"Prohibido estacionar", forma:"circulo_prohibicion", icono:{tipo:"letra", valor:"E", tachada:true} },
{ id:"r10", categoria:"Reglamentación", nombre:"Prohibido estacionar y detenerse", forma:"circulo_prohibicion", icono:{tipo:"letra", valor:"E", tachada:true, doble:true} },
{ id:"r11", categoria:"Reglamentación", nombre:"Prohibido circular peatones", forma:"circulo_prohibicion", icono:{tipo:"persona", pose:"caminando", tachada:true} },
{ id:"r12", categoria:"Reglamentación", nombre:"Prohibido circular camiones", forma:"circulo_prohibicion", icono:{tipo:"vehiculo", variante:"camion", tachada:true} },
{ id:"r13", categoria:"Reglamentación", nombre:"Prohibido circular automotores", forma:"circulo_prohibicion", icono:{tipo:"vehiculo", variante:"auto", tachada:true} },
{ id:"r14", categoria:"Reglamentación", nombre:"Prohibido circular bicicletas", forma:"circulo_prohibicion", icono:{tipo:"vehiculo", variante:"bicicleta", tachada:true} },
{ id:"r15", categoria:"Reglamentación", nombre:"Prohibido tracción a sangre", forma:"circulo_prohibicion", icono:{tipo:"pictograma", nombre:"carro_caballo", tachada:true} },
{ id:"r16", categoria:"Reglamentación", nombre:"Prohibido adelantar", forma:"circulo_prohibicion", icono:{tipo:"pictograma", nombre:"adelantar", tachada:true} },
{ id:"r17", categoria:"Reglamentación", nombre:"Conserve su derecha", forma:"circulo_obligacion", icono:{tipo:"flecha", rotacion:45} },
{ id:"r18", categoria:"Reglamentación", nombre:"Carga máxima permitida", forma:"circulo_prohibicion", icono:{tipo:"numero", valor:"6tn"} },
{ id:"r19", categoria:"Reglamentación", nombre:"Altura máxima permitida", forma:"circulo_prohibicion", icono:{tipo:"numero", valor:"4m", arriba:true} },
{ id:"r20", categoria:"Reglamentación", nombre:"Ancho máximo permitido", forma:"circulo_prohibicion", icono:{tipo:"numero", valor:"1,80m", flechas:true} },
{ id:"r21", categoria:"Reglamentación", nombre:"Velocidad máxima en calles, zonas urbanas", forma:"circulo_prohibicion", icono:{tipo:"numero", valor:"40"} },
{ id:"r22", categoria:"Reglamentación", nombre:"Curva muy peligrosa", forma:"triangulo", icono:{tipo:"camino", variante:"curva_cerrada"} },
{ id:"r23", categoria:"Reglamentación", nombre:"Preferencia de avance", forma:"diamante_doble", icono:{tipo:"pictograma", nombre:"preferencia"} },
{ id:"r24", categoria:"Reglamentación", nombre:"Giro a la derecha", forma:"circulo_obligacion", icono:{tipo:"flecha", curva:true, rotacion:0} },
{ id:"r25", categoria:"Reglamentación", nombre:"Giro a la izquierda", forma:"circulo_obligacion", icono:{tipo:"flecha", curva:true, rotacion:0, espejo:true} },
{ id:"r26", categoria:"Reglamentación", nombre:"Límite por eje", forma:"circulo_prohibicion", icono:{tipo:"numero", valor:"2t", eje:true} },
{ id:"r27", categoria:"Reglamentación", nombre:"Prohibido jinete", forma:"circulo_prohibicion", icono:{tipo:"pictograma", nombre:"jinete", tachada:true} },
{ id:"r28", categoria:"Reglamentación", nombre:"Doble circulación", forma:"circulo_obligacion", icono:{tipo:"flecha", doble:true, rotacion:-90} },
{ id:"r29", categoria:"Reglamentación", nombre:"Circulación obligatoria (derecha)", forma:"circulo_obligacion", icono:{tipo:"flecha", rotacion:0} },
{ id:"r30", categoria:"Reglamentación", nombre:"Prohibido pasar sin detenerse", forma:"circulo_prohibicion", icono:{tipo:"barra"} },
{ id:"r31", categoria:"Reglamentación", nombre:"Prohibido circular maquinaria agrícola", forma:"circulo_prohibicion", icono:{tipo:"pictograma", nombre:"tractor", tachada:true} },
{ id:"r32", categoria:"Reglamentación", nombre:"Circulación obligatoria (de frente)", forma:"circulo_obligacion", icono:{tipo:"flecha", rotacion:-90} },
{ id:"r33", categoria:"Reglamentación", nombre:"Paso obligatorio (diagonal derecha)", forma:"circulo_obligacion", icono:{tipo:"flecha", rotacion:-45} },
{ id:"r34", categoria:"Reglamentación", nombre:"Paso obligatorio (diagonal izquierda)", forma:"circulo_obligacion", icono:{tipo:"flecha", rotacion:-135} },
{ id:"r35", categoria:"Reglamentación", nombre:"Fin de la prescripción", forma:"circulo_fin", icono:{tipo:"barra", diagonal:true} },
{ id:"r36", categoria:"Reglamentación", nombre:"Estacionamiento limitado", forma:"circulo_obligacion", icono:{tipo:"letra", valor:"E"} },
{ id:"r37", categoria:"Reglamentación", nombre:"Peatones por la izquierda", forma:"circulo_obligacion", icono:{tipo:"persona", pose:"caminando", espejo:true} },
{ id:"r38", categoria:"Reglamentación", nombre:"Tránsito pesado a la derecha", forma:"circulo_obligacion", icono:{tipo:"vehiculo", variante:"camion"} },
{ id:"r39", categoria:"Reglamentación", nombre:"Largo máximo permitido", forma:"circulo_prohibicion", icono:{tipo:"numero", valor:"20m", flechas:true} },
{ id:"r40", categoria:"Reglamentación", nombre:"Uso obligatorio de cadenas para la nieve", forma:"circulo_obligacion", icono:{tipo:"pictograma", nombre:"cadenas"} },
{ id:"r41", categoria:"Reglamentación", nombre:"Circulación exclusiva (bicicletas)", forma:"circulo_obligacion", icono:{tipo:"vehiculo", variante:"bicicleta"} },
{ id:"r42", categoria:"Reglamentación", nombre:"Velocidad máxima en caso de niebla (40)", forma:"circulo_niebla", icono:{tipo:"numero", valor:"40"} },
{ id:"r43", categoria:"Reglamentación", nombre:"Velocidad máxima en caso de niebla (60)", forma:"circulo_niebla", icono:{tipo:"numero", valor:"60"} },
{ id:"r44", categoria:"Reglamentación", nombre:"Velocidad mínima permitida", forma:"circulo_obligacion", icono:{tipo:"numero", valor:"35"} },
{ id:"r45", categoria:"Reglamentación", nombre:"Circulación exclusiva (colectivos)", forma:"circulo_obligacion", icono:{tipo:"vehiculo", variante:"bus"} },
{ id:"r46", categoria:"Reglamentación", nombre:"Fin de la prescripción (ej: fin de velocidad mínima)", forma:"circulo_fin", icono:{tipo:"numero", valor:"35", tachada:true} },
{ id:"r47", categoria:"Reglamentación", nombre:"Estacionamiento reglamentado", forma:"circulo_obligacion", icono:{tipo:"letra", valor:"E"} },
{ id:"r48", categoria:"Reglamentación", nombre:"Circulación obligatoria (rectangular)", forma:"rectangulo_obligacion", icono:{tipo:"flecha", rotacion:0} },

// ---------------- INFORMACIÓN (rectángulo azul) ----------------
{ id:"i01", categoria:"Información", nombre:"Puesto de socorro", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"cruz"} },
{ id:"i02", categoria:"Información", nombre:"Aeropuerto", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"avion"} },
{ id:"i03", categoria:"Información", nombre:"Servicio mecánico", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"llave"} },
{ id:"i04", categoria:"Información", nombre:"Servicio telefónico", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"telefono"} },
{ id:"i05", categoria:"Información", nombre:"Hotel", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"cama"} },
{ id:"i06", categoria:"Información", nombre:"Restaurante", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"cubiertos"} },
{ id:"i07", categoria:"Información", nombre:"Estación de servicio", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"surtidor"} },
{ id:"i08", categoria:"Información", nombre:"Playa de estacionamiento", forma:"rectangulo_info", icono:{tipo:"letra", valor:"E"} },
{ id:"i09", categoria:"Información", nombre:"Estacionamiento para casas rodantes", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"casilla"} },
{ id:"i10", categoria:"Información", nombre:"Policía", forma:"rectangulo_info", icono:{tipo:"persona", pose:"parado"} },
{ id:"i11", categoria:"Información", nombre:"Playa", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"sombrilla"} },
{ id:"i12", categoria:"Información", nombre:"Balneario", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"ondas"} },
{ id:"i13", categoria:"Información", nombre:"Zona de detención de ómnibus", forma:"rectangulo_info", icono:{tipo:"vehiculo", variante:"bus"} },
{ id:"i14", categoria:"Información", nombre:"Taxi", forma:"rectangulo_info", icono:{tipo:"vehiculo", variante:"auto"} },
{ id:"i15", categoria:"Información", nombre:"Camping", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"carpa"} },
{ id:"i16", categoria:"Información", nombre:"Servicios sanitarios", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"sanitarios"} },
{ id:"i17", categoria:"Información", nombre:"Zona reservada para discapacitados", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"silla_ruedas"} },
{ id:"i18", categoria:"Información", nombre:"Correo", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"sobre"} },
{ id:"i19", categoria:"Información", nombre:"Gomería", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"rueda"} },
{ id:"i20", categoria:"Información", nombre:"Bar", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"taza"} },
{ id:"i21", categoria:"Información", nombre:"Punto panorámico", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"montana"} },
{ id:"i22", categoria:"Información", nombre:"Telesférico", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"telesferico"} },
{ id:"i23", categoria:"Información", nombre:"Lugar para recreación y descanso", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"mesa"} },
{ id:"i24", categoria:"Información", nombre:"Hotel (H)", forma:"rectangulo_info", icono:{tipo:"letra", valor:"H"} },
{ id:"i25", categoria:"Información", nombre:"Terminal de ómnibus", forma:"rectangulo_info", icono:{tipo:"vehiculo", variante:"bus"} },
{ id:"i26", categoria:"Información", nombre:"Estación de ferrocarril", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"tren"} },
{ id:"i27", categoria:"Información", nombre:"Museo", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"museo"} },
{ id:"i28", categoria:"Información", nombre:"Estacionamiento permitido", forma:"rectangulo_info", icono:{tipo:"letra", valor:"E"} },
{ id:"i29", categoria:"Información", nombre:"Circulación obligatoria (derecha, informativa)", forma:"rectangulo_info", icono:{tipo:"flecha", rotacion:0} },
{ id:"i30", categoria:"Información", nombre:"Circulación obligatoria (izquierda, informativa)", forma:"rectangulo_info", icono:{tipo:"flecha", rotacion:180} },
{ id:"i31", categoria:"Información", nombre:"Direcciones permitidas (arriba y derecha)", forma:"rectangulo_info", icono:{tipo:"flecha", doble:true, rotacion:-45} },
{ id:"i32", categoria:"Información", nombre:"Direcciones permitidas (arriba e izquierda)", forma:"rectangulo_info", icono:{tipo:"flecha", doble:true, rotacion:-135} },
{ id:"i33", categoria:"Información", nombre:"Circulación obligatoria (rotonda)", forma:"rectangulo_info", icono:{tipo:"camino", variante:"rotonda"} },
{ id:"i34", categoria:"Información", nombre:"Direcciones permitidas (Y)", forma:"rectangulo_info", icono:{tipo:"camino", variante:"y"} },
{ id:"i35", categoria:"Información", nombre:"Circulación obligatoria, giro derecha", forma:"rectangulo_info", icono:{tipo:"flecha", curva:true, rotacion:0} },
{ id:"i36", categoria:"Información", nombre:"Autopista", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"autopista"} },
{ id:"i37", categoria:"Información", nombre:"Designación de autopista", forma:"rectangulo_info", icono:{tipo:"texto", valor:"AU 1"} },
{ id:"i38", categoria:"Información", nombre:"Indicador de recorridos y caminos", forma:"rectangulo_verde", icono:{tipo:"pictograma", nombre:"recorrido"} },
{ id:"i39", categoria:"Información", nombre:"Nomenclatura urbana", forma:"rectangulo_blanco", icono:{tipo:"texto", valor:"Av. Cazón"} },
{ id:"i40", categoria:"Información", nombre:"Cartel de ruta (localidad y distancia)", forma:"rectangulo_blanco", icono:{tipo:"texto", valor:"Rosario"} },
{ id:"i41", categoria:"Información", nombre:"Camino o calle sin salida", forma:"rectangulo_info", icono:{tipo:"camino", variante:"sin_salida"} },
{ id:"i42", categoria:"Información", nombre:"Velocidades máximas permitidas", forma:"rectangulo_info", icono:{tipo:"numero", valor:"#"} },
{ id:"i43", categoria:"Información", nombre:"Camino o paso intransitable", forma:"rectangulo_rojo", icono:{tipo:"texto", valor:"CERRADO"} },
{ id:"i44", categoria:"Información", nombre:"Camino o paso transitable", forma:"rectangulo_verde", icono:{tipo:"texto", valor:"ABIERTO"} },
{ id:"i45", categoria:"Información", nombre:"Ruta nacional", forma:"escudo_nacional", icono:{tipo:"numero", valor:"9"} },
{ id:"i46", categoria:"Información", nombre:"Ruta provincial", forma:"escudo_provincial", icono:{tipo:"numero", valor:"4"} },
{ id:"i47", categoria:"Información", nombre:"Mojón kilométrico", forma:"mojon", icono:{tipo:"numero", valor:"355"} },
{ id:"i48", categoria:"Información", nombre:"Desvío por cambio de sentido", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"desvio"} },
{ id:"i49", categoria:"Información", nombre:"Orientación (caminos primarios y secundarios)", forma:"rectangulo_verde", icono:{tipo:"texto", valor:"Pilar / San Isidro"} },
{ id:"i50", categoria:"Información", nombre:"Fin de autopista", forma:"rectangulo_info", icono:{tipo:"pictograma", nombre:"autopista", tachada:true} },
{ id:"i51", categoria:"Información", nombre:"Comienzo o fin de zona urbana", forma:"rectangulo_blanco", icono:{tipo:"texto", valor:"Bariloche"} },
{ id:"i52", categoria:"Información", nombre:"Identificación de jurisdicción o accidente geográfico", forma:"rectangulo_blanco", icono:{tipo:"texto", valor:"Misiones"} },
{ id:"i53", categoria:"Información", nombre:"Hipoacusia", forma:"rectangulo_info", icono:{tipo:"patron", variante:"cuadros"} },
{ id:"i54", categoria:"Información", nombre:"Víctima de accidente de tránsito (Memoria)", forma:"rectangulo_blanco", icono:{tipo:"pictograma", nombre:"estrella"} },

// ---------------- SEÑALES TRANSITORIAS (naranja) ----------------
{ id:"t01", categoria:"Transitorias", nombre:"Calle o carretera en construcción o cerrada", forma:"rectangulo_transitoria", icono:{tipo:"texto", valor:"EN CONSTRUCCIÓN"} },
{ id:"t02", categoria:"Transitorias", nombre:"Desvío", forma:"rectangulo_transitoria", icono:{tipo:"flecha", rotacion:-45} },
{ id:"t03", categoria:"Transitorias", nombre:"Longitud de la construcción", forma:"rectangulo_transitoria", icono:{tipo:"texto", valor:"15 KM"} },
{ id:"t04", categoria:"Transitorias", nombre:"Zona de explosivos", forma:"rectangulo_transitoria", icono:{tipo:"pictograma", nombre:"explosivo"} },
{ id:"t05", categoria:"Transitorias", nombre:"Fin de construcción", forma:"rectangulo_transitoria", icono:{tipo:"texto", valor:"FIN"} },
{ id:"t06", categoria:"Transitorias", nombre:"Carretera de un solo carril", forma:"rectangulo_transitoria", icono:{tipo:"camino", variante:"angosto"} },
{ id:"t07", categoria:"Transitorias", nombre:"Hombres trabajando sobre banquina", forma:"rombo_transitoria", icono:{tipo:"persona", pose:"trabajando"} },
{ id:"t08", categoria:"Transitorias", nombre:"Hombres trabajando", forma:"rombo_transitoria", icono:{tipo:"persona", pose:"trabajando"} },
{ id:"t09", categoria:"Transitorias", nombre:"Banderillero", forma:"rombo_transitoria", icono:{tipo:"persona", pose:"banderillero"} },
{ id:"t10", categoria:"Transitorias", nombre:"Calzada estrecha", forma:"rombo_transitoria", icono:{tipo:"camino", variante:"angosto"} },
{ id:"t11", categoria:"Transitorias", nombre:"Equipo pesado en la vía", forma:"rombo_transitoria", icono:{tipo:"pictograma", nombre:"excavadora"} },
{ id:"t12", categoria:"Transitorias", nombre:"Vallas (tipo 1)", forma:"objeto_transitoria", icono:{tipo:"pictograma", nombre:"valla1"} },
{ id:"t13", categoria:"Transitorias", nombre:"Vallas (tipo 2)", forma:"objeto_transitoria", icono:{tipo:"pictograma", nombre:"valla2"} },
{ id:"t14", categoria:"Transitorias", nombre:"Vallas (tipo 3)", forma:"objeto_transitoria", icono:{tipo:"pictograma", nombre:"valla3"} },
{ id:"t15", categoria:"Transitorias", nombre:"Delineadores", forma:"objeto_transitoria", icono:{tipo:"pictograma", nombre:"delineador"} },
{ id:"t16", categoria:"Transitorias", nombre:"Tambores", forma:"objeto_transitoria", icono:{tipo:"pictograma", nombre:"tambor"} },
{ id:"t17", categoria:"Transitorias", nombre:"Conos", forma:"objeto_transitoria", icono:{tipo:"pictograma", nombre:"cono"} },

// ---------------- SEÑALES HORIZONTALES (sobre asfalto) ----------------
{ id:"h01", categoria:"Horizontales", nombre:"Dividen las corrientes circulatorias, prohibido adelantarse", forma:"rectangulo_horizontal", icono:{tipo:"marca", variante:"doble_solida"} },
{ id:"h02", categoria:"Horizontales", nombre:"Zona reservada al peatón para cruzar la calzada", forma:"rectangulo_horizontal", icono:{tipo:"marca", variante:"cebra"} },
{ id:"h03", categoria:"Horizontales", nombre:"Separa el tránsito en el mismo sentido, prohibido adelantamiento", forma:"rectangulo_horizontal", icono:{tipo:"marca", variante:"solida_simple"} },
{ id:"h04", categoria:"Horizontales", nombre:"Ordena circulación de carriles, permite adelantamiento", forma:"rectangulo_horizontal", icono:{tipo:"marca", variante:"discontinua"} },
{ id:"h05", categoria:"Horizontales", nombre:"Detener vehículo antes de la línea", forma:"rectangulo_horizontal", icono:{tipo:"marca", variante:"linea_detencion"} },
{ id:"h06", categoria:"Horizontales", nombre:"Sentido de la circulación y anticipan los giros permitidos", forma:"rectangulo_horizontal", icono:{tipo:"marca", variante:"flecha_pavimento"} },
{ id:"h07", categoria:"Horizontales", nombre:"Señalamiento en curvas", forma:"rectangulo_horizontal", icono:{tipo:"marca", variante:"curva_pavimento"} },
{ id:"h08", categoria:"Horizontales", nombre:"Anticipan el destino de la próxima vía para poder acceder", forma:"rectangulo_horizontal", icono:{tipo:"marca", variante:"chevron_pavimento"} },
{ id:"h09", categoria:"Horizontales", nombre:"Líneas marcadoras de zona para estacionar", forma:"rectangulo_horizontal", icono:{tipo:"marca", variante:"bahia"} },
{ id:"h10", categoria:"Horizontales", nombre:"Línea discontinua puede traponerse, contrario al de la otra línea", forma:"rectangulo_horizontal", icono:{tipo:"marca", variante:"mixta"} },
{ id:"h11", categoria:"Horizontales", nombre:"Dividen las corrientes circulatorias, prohibido adelantarse (doble)", forma:"rectangulo_horizontal", icono:{tipo:"marca", variante:"doble_solida"} },
{ id:"h12", categoria:"Horizontales", nombre:"Líneas demarcadoras de obstáculos", forma:"rectangulo_horizontal", icono:{tipo:"marca", variante:"obstaculo"} },
{ id:"h13", categoria:"Horizontales", nombre:"Marcan la proximidad", forma:"rectangulo_horizontal", icono:{tipo:"marca", variante:"proximidad"} },
{ id:"h14", categoria:"Horizontales", nombre:"Señalamiento de una intersección urbana", forma:"rectangulo_horizontal", icono:{tipo:"marca", variante:"interseccion"} },

// ---------------- SEMÁFOROS ----------------
{ id:"s01", categoria:"Semáforos", nombre:"Luz verde = avanzar", forma:"circulo_semaforo", icono:{tipo:"luz", color:"verde"} },
{ id:"s02", categoria:"Semáforos", nombre:"Luz amarilla intermitente = precaución / luz amarilla fija = detenerse o despejar el cruce", forma:"circulo_semaforo", icono:{tipo:"luz", color:"amarilla"} },
{ id:"s03", categoria:"Semáforos", nombre:"Luz roja = detenerse", forma:"circulo_semaforo", icono:{tipo:"luz", color:"roja"} },
{ id:"s04", categoria:"Semáforos", nombre:"Luz roja peatonal = no debe cruzar / luz verde = puede cruzar", forma:"circulo_semaforo", icono:{tipo:"luz_peaton"} },
{ id:"s05", categoria:"Semáforos", nombre:"Luz roja con flecha = prohibido girar / luz verde con flecha = autoriza el giro", forma:"circulo_semaforo", icono:{tipo:"luz_flecha"} },

// ---------------- SEÑALES DE AGENTE ----------------
{ id:"a01", categoria:"Señales de agente", nombre:"Detenerse (= luz roja)", forma:"figura_agente", icono:{tipo:"agente", pose:"brazos_lados_frente"} },
{ id:"a02", categoria:"Señales de agente", nombre:"Precaución (= luz amarilla)", forma:"figura_agente", icono:{tipo:"agente", pose:"brazo_arriba"} },
{ id:"a03", categoria:"Señales de agente", nombre:"Avanzar (= luz verde)", forma:"figura_agente", icono:{tipo:"agente", pose:"espalda"} },
{ id:"a04", categoria:"Señales de agente", nombre:"Continuar a la derecha o izquierda", forma:"figura_agente", icono:{tipo:"agente", pose:"brazo_lateral"} },
{ id:"a05", categoria:"Señales de agente", nombre:"Detenerse a la derecha o izquierda", forma:"figura_agente", icono:{tipo:"agente", pose:"brazo_frente_palma"} },
{ id:"a06", categoria:"Señales de agente", nombre:"Apurar a la derecha o izquierda", forma:"figura_agente", icono:{tipo:"agente", pose:"brazo_giratorio"} },
{ id:"a07", categoria:"Señales de agente", nombre:"Parar de frente", forma:"figura_agente", icono:{tipo:"agente", pose:"frente_brazo_arriba"} },
{ id:"a08", categoria:"Señales de agente", nombre:"Pasar por detrás", forma:"figura_agente", icono:{tipo:"agente", pose:"perfil_brazo_atras"} },
{ id:"a09", categoria:"Señales de agente", nombre:"Pasar por delante", forma:"figura_agente", icono:{tipo:"agente", pose:"perfil_brazo_adelante"} },

];

if (typeof module !== "undefined") { module.exports = SENALES; }
